# Generated by Django 3.0.5 on 2020-05-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20200224_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_field', models.UUIDField()),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='track',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='brand_logo',
            field=models.ImageField(upload_to='brand_logo/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('options', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Property')),
            ],
            options={
                'db_table': 'webhooks',
            },
        ),
        migrations.CreateModel(
            name='DoNotTrackIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Property')),
            ],
            options={
                'db_table': 'do_not_track_ip',
            },
        ),
        migrations.CreateModel(
            name='DoNotTrackEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Property')),
            ],
            options={
                'db_table': 'do_not_track_email',
            },
        ),
        migrations.CreateModel(
            name='CustomizeAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_threshold', models.CharField(max_length=150)),
                ('app_uid', models.CharField(max_length=150)),
                ('app_type', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Property')),
            ],
            options={
                'db_table': 'customize_alerts',
            },
        ),
    ]
